---
intellij_download_dir: "{{ x_ansible_download_dir | default(ansible_env.HOME + '/.ansible/tmp/downloads') }}"
intellij_filename: "{{ intellij_edition }}-{{ intellij_version }}.tar.gz"
intellij_download_url: "http://download.jetbrains.com/idea/{{ intellij_filename }}"
intellij_download_path: "{{ intellij_download_dir }}/{{ intellij_filename }}"
