---
- hosts: localhost
  pre_tasks:
    - name: update repositories
      become: yes
      apt: update_cache=yes
      changed_when: False

  tasks:
    - include: tasks/packages.yml
    - include: tasks/home.yml
    - include: tasks/system-config.yml
