---
- name: Switch from Debian stable to Debian testing
  hosts: all
  vars:
    apt_repositories:
      - file: debian-main
        repo: deb http://deb.debian.org/debian/ testing main contrib non-free
      - file: debian-updates
        repo: deb http://deb.debian.org/debian/ testing-updates main contrib non-free
      - file: debian-security
        repo: deb http://deb.debian.org/debian-security testing-security main
  roles:
    - add-apt-repo
    - system-upgrade
  tags:
    - basic-system
    - debian-upgrade

- name: Configure some low-level settings
  hosts: all
  vars:
    blacklisted_modules: [ pcspkr ]
  roles:
    - blacklist-modules
    - keyboard
  tags:
    - basic-system
    - settings

- name: Install requirements for Ansible
  hosts: all
  become: yes
  tasks:
    - name: Ensure python3-pip is installed
      apt:
        update_cache: yes
        name:
          - python3-pip
    - name: Ensure pexpect is installed
      pip:
        name: pexpect
  tags:
    - basic-system
    - ansible-requirements

- name: Install required packages from apt
  hosts: all
  roles: [ apt-install ]
  tags:
    - basic-system
    - apt-install

- name: Install and configure zsh + oh-my-zsh
  hosts: all
  roles: [ zsh ]
  tags:
    - basic-system
    - zsh

- name: Create and deploy a new SSH key
  hosts: all
  roles: [ ssh-key ]
  tags:
    - basic-system
    - ssh-key

- name: Prepare my home directory
  hosts: all
  roles: [ homedir ]
  tags:
    - basic-system
    - homedir

- name: Setup my dotfiles
  hosts: all
  vars_prompt:
    - name: "gpg_passphrase"
      prompt: "Enter GPG passphrase"
      private: yes
  roles: [ dotfiles ]
  tags:
    - basic-system
    - dotfiles

- name: Setup my personal scripts
  hosts: all
  roles: [ my-utils ]
  tags:
    - basic-system
    - my-utils

- name: Install Greenclip
  hosts: all
  roles: [ greenclip ]
  tags:
    - basic-system
    - greenclip

- name: Install Anki
  hosts: all
  roles: [ anki ]
  tags:
    - basic-system
    - anki

- name: Install TinyTex
  hosts: all
  roles: [ tinytex ]
  tags: tinytex

- name: Install Java
  hosts: all
  roles: [ apt-install ]
  vars:
    apt_packages:
      - openjdk-11-jdk
      - maven
      - gradle
  tags: java

- name: Install IntelliJ
  hosts: all
  roles: [ intellij ]
  tags: intellij

- name: Install Skype
  hosts: all
  roles: [ skype ]
  tags: skype

- name: Install Signal
  hosts: all
  roles: [ signal-desktop ]
  tags: signal

- name: Prepare Common Lisp environment
  hosts: all
  roles: [ apt-install ]
  vars:
    apt_packages:
      - sbcl
  tags: common-lisp
