---
- hosts: localhost
  roles:
    - ansible-requirements
    - nox-packages
    - {role: "x-packages", tags: "x"}
    - system-config
    - zsh
    - home
    - my-utils
    - dotfiles
    - {role: "java", tags: "java"}
  vars_prompt:
    - name: "gpg_passphrase"
      prompt: "Enter GPG passphrase"
      private: yes
