---

###
### Bootstrap System
###
- hosts: localhost
  roles:
    - dist-upgrade
  tags:
    - dist-upgrade

- hosts: localhost
  roles:
    - ansible-requirements
    - nox-packages
    - {role: "x-packages", tags: "x"}
    - system-config
    - zsh
    - home
    - my-utils
    - dotfiles
    - {role: "java", tags: "java"}
  tags:
    - main
  vars_prompt:
    - name: "gpg_passphrase"
      prompt: "Enter GPG passphrase"
      private: yes
