#+TITLE: Ansible Desktop

This repository aims at automating the setup of my Debian workstations
using a combination of [[https://www.ansible.com/][Ansible]] + my [[https://github.com/alecigne/dotfiles][dotfiles]].

* Installing Debian

1. Download a =netinst= ISO image from the [[https://www.debian.org/distrib/netinst][official website]].

2. Create a bootable USB drive:

   #+begin_src sh
     sudo dd if=[path_to_iso] of=[path_to_usb]
   #+end_src

   I usually use =sudo fdisk -l= to know the path to the USB
   drive. *Be careful*, as choosing the wrong path here might cause
   serious damage.

3. Install Debian. This can be [[https://www.debian.org/releases/buster/amd64/apb.en.html][automated too]]! I install only the
   standard system utilities.

* Manual steps

There are still a few manual steps, that I hope I will get rid of with
time.

1. [as root] Edit =/etc/apt/sources.list=:

   #+begin_src conf
     deb http://deb.debian.org/debian/ [debian-version] main contrib non-free
     deb-src http://deb.debian.org/debian/ [debian-version] main contrib non-free
   #+end_src

   =debian-version= must be replaced with the version of Debian that I
   want to install, usually =testing= or =unstable=.

2. [as root] Upgrade the system:

   #+begin_src sh
     apt update && apt upgrade
   #+end_src

3. [as root] Install Ansible, Git and sudo:

   #+begin_src sh
     apt install ansible git sudo
   #+end_src

4. [as root] Add yourself to the =sudoers= file:

   #+begin_src sh
     echo "alc ALL=(ALL:ALL) ALL" > /etc/sudoers.d/alc
   #+end_src

5. Clone the repository and launch the Ansible playbook as a user:

   #+begin_src sh
     ansible-playbook local.yml -K
   #+end_src

   Ansible will use =sudo= when required. =-K= will ask for the user
   password.

* About =ansible-pull=

From the Ansible documentation:

#+begin_quote
The ansible-pull is a small script that will checkout a repo of
configuration instructions from git, and then run ansible-playbook
against that content.
#+end_quote

Thus, I can also launch the script with:

#+begin_src sh
  ansible-pull -U https://github.com/alecigne/ansible-desktop.git -K -C [branch]
#+end_src

I prefer the more detailed output of =ansible-playbook=.

* Tasks

- [ ] Pull dotfiles submodules. The new workstation must register
  itself to Github (SSH key) or a SSH keypair must be created
  beforehand as a manual step.

- [ ] Do not re-execute Stow every time

- Packages to add:

  + [ ] =veracrypt= \\
    Check [[https://github.com/rodrigorega/ansible-role-VeraCrypt/blob/master/tasks/main.yml][this]].
