- name: Install packages from apt
  become: yes
  become_method: sudo
  apt:
    pkg:
      - alttab
      - aptitude
      - borgbackup
      - emacs
      - feh
      - firefox
      - ghostscript
      - gnupg
      - i3
      - imagemagick
      - ledger
      - mupdf
      - ncdu
      - network-manager
      - numlockx
      - pandoc
      - pass
      - redshift
      - restic
      - rofi
      - rxvt-unicode
      - stow
      - tmux
      - tree
      - vlc
      - xclip
      - xorg
      - zsh
    state: present

- name: Install oh-my-zsh
  git:
    repo: https://github.com/robbyrussell/oh-my-zsh
    dest: ~/.oh-my-zsh
    force: yes

- name: Install powerlevel10k
  git:
    repo: https://github.com/romkatv/powerlevel10k
    depth: 1
    dest: ~/.oh-my-zsh/custom/themes/powerlevel10k
    force: yes

- name: Clone personal utils
  git:
    repo: https://github.com/alecigne/my-utils.git
    dest: "{{ ansible_env.HOME }}/src/scripts"

- name: Find personal scripts
  find:
    paths: "{{ ansible_env.HOME }}/src/scripts"
    patterns: "*.bash"
  register: find

- name: Symlink personal scripts
  file:
    src: "{{ item.path }}"
    path: "{{ ansible_env.HOME }}/bin/{{ (item.path | basename | splitext)[0] }}"
    state: link
  with_items: "{{ find.files }}"
