- name: Install packages from apt
  become: yes
  become_method: sudo
  apt:
    pkg:
      - alttab
      - aptitude
      - emacs
      - feh
      - firefox
      - ghostscript
      - gnupg
      - i3
      - imagemagick
      - ledger
      - mupdf
      - ncdu
      - network-manager
      - numlockx
      - pandoc
      - pass
      - redshift
      - restic
      - rofi
      - rxvt-unicode
      - stow
      - tmux
      - tree
      - vlc
      - xclip
      - xorg
      - zsh
    state: present
