---
- name: Ensure github.com is a known host
  lineinfile:
    dest: ~/.ssh/known_hosts
    create: yes
    state: present
    line: "{{ lookup('pipe', 'ssh-keyscan -t ed25519 github.com') }}"
    regexp: "^github\\.com"

- name: Clone dotfiles
  git:
    repo: "{{ dotfiles_repo }}"
    dest: "{{ dotfiles_dir }}"
    update: no
    # Do not init submodules - some of them can be unreachable (local network)
    recursive: no

- name: Init/update submodules from Github
  command: chdir="{{ dotfiles_dir }}" git submodule update --init -- emacs/.emacs.d stumpwm/.stumpwm.d
  register: update_github_submodules
  changed_when: update_github_submodules.stdout != ""

- name: Stow configurations
  expect:
    chdir: "{{ dotfiles_dir }}"
    command: bash stow.bash
    responses:
      (?i)passphrase: "{{ gpg_passphrase }}"
  register: stow_result
  changed_when: stow_result.stdout != ""

- name: Apply correct permissions to .gnupg dirs (700)
  command: find {{ ansible_env.HOME }}/.gnupg -type d -exec chmod -c 700 {} \;
  register: chmod_result
  changed_when: chmod_result.stdout != ""

- name: Apply correct permissions to .gnupg files (600)
  command: find -L {{ ansible_env.HOME }}/.gnupg -type f -exec chmod -c 600 {} \;
  register: chmod_result
  changed_when: chmod_result.stdout != ""
