---
directories:
  - "{{ bin_dir }}"
  - "{{ dat_dir }}"
  - "{{ etc_dir }}"
  - "{{ ibx_dir }}"
  - "{{ med_dir }}"
  - "{{ mnt_dir }}"
  - "{{ org_dir }}"
  - "{{ pub_dir }}"
  - "{{ src_dir }}"
  - "{{ tmp_dir }}"
  - "{{ tmp_dir }}/screenshots"
drone_zone_url: https://somafm.com/dronezone256.pls
drone_zone_file: "{{ med_dir }}/dz.pls"
