---
- name: Create download directory
  file:
    state: directory
    dest: "{{ intellij_download_dir }}"

- name: Download IntelliJ
  get_url:
    url: "{{ intellij_download_url }}"
    dest: "{{ intellij_download_dir }}/{{ intellij_filename }}"

- name: Create installation directory
  file:
    state: directory
    dest: "{{ intellij_install_dir }}"

- name: Extract IntelliJ in installation directory
  unarchive:
    src: "{{ intellij_download_path }}"
    extra_opts: "--strip-components=1"
    dest: "{{ intellij_install_dir }}"
    creates: "{{ intellij_install_dir }}/bin"

- name: Symlink IntelliJ binary
  file:
    src: "{{ intellij_install_dir }}/bin/idea.sh"
    path: "{{ bin_dir }}/intellij"
    state: link
