---
- name: Check if IntelliJ is installed in homedir
  stat:
    path: "{{ intellij_install_dir }}/bin/idea.sh"
  register: intellij_binary

- name: Install IntelliJ
  include_tasks: intellij.yml
  when: not intellij_binary.stat.exists
