---

- name: Update apt cache
  apt:
    update_cache: yes
  register: result
  until: result is succeeded
  retries: 30
  delay: 10
  become: yes

- name: Upgrade the system
  apt:
    upgrade: dist
  become: yes

- name: Check if a reboot is required
  stat: path=/var/run/reboot-required get_md5=no
  register: reboot_flag

- name: Reboot the server
  reboot:
    reboot_timeout: 300
  when: reboot_flag.stat.exists
