---

- name: Delete default sources.list
  file:
    state: absent
    path: /etc/apt/sources.list
  become: yes

- name: Create new sources.list
  apt_repository:
    state: present
    repo: "{{ item.repo }}"
    filename: "{{ item.file }}"
    validate_certs: True
    update_cache: True
  register: task_result
  until: task_result is succeeded
  retries: 30
  delay: 10
  become: True
  with_items:
    - "{{ apt_repositories }}"

- name: Upgrade the system
  apt:
    update_cache: yes
    upgrade: dist
  become: yes
