---
- name: Install zsh
  include_role:
    name: apt-install
  vars:
    apt_packages: zsh

- name: Get zsh path
  command: which zsh
  register: zsh_path
  changed_when: false

- name: Change shell to zsh
  user: name=alc shell={{ zsh_path.stdout }}
  become: yes

- name: Remove non-zsh dotfiles
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "{{ ansible_env.HOME }}/.bashrc"
    - "{{ ansible_env.HOME }}/.profile"

- name: Install oh-my-zsh
  git:
    repo: "{{ oh_my_zsh_repo }}"
    dest: "{{ oh_my_zsh_dest }}"
    # Any modified files in the working repository will be discarded
    force: yes

- name: Install powerlevel10k
  git:
    repo: "{{ powerlevel10k_repo }}"
    depth: 1
    dest: "{{ powerlevel10k_dest }}"
    force: yes
