---
- name: Check if TinyTeX is already installed
  stat:
    path: "{{ tinytex_dir }}"
  register: tinytex_result

- name: Execute TinyTeX installation script
  when: not tinytex_result.stat.exists
  shell: "wget -qO- {{ tinytex_download_url }} | sh"

- name: Store installed packages
  shell: "tlmgr list --only-installed | cut -f1 -d \":\" | cut -c 3- | tr '\r\n' ' '"
  register: tinytex_installed_packages

- name: Install LaTeX packages
  command: "tlmgr install {{ item }}"
  with_items: "{{ tinytex_required_packages }}"
  when: not item in tinytex_installed_packages.stdout
