---

- name: Ensure default sources.list is absent
  file:
    state: absent
    path: /etc/apt/sources.list
  become: yes
  notify: Update apt cache

- name: Ensure apt keys are managed
  apt_key:
    state: "{{ apt_repo_state }}"
    id: "{{ item.id | default(omit) }}"
    file: "{{ item.file | default(omit) }}"
    keyserver: "{{ item.keyserver | default(omit) }}"
    url: "{{ item.url | default(omit) }}"
    validate_certs: yes
  register: result
  until: result is succeeded
  retries: 30
  delay: 10
  become: yes
  with_items:
    - "{{ apt_repo_keys }}"
  notify: Update apt cache

- name: Ensure apt repositories are managed
  apt_repository:
    state: "{{ apt_repo_state }}"
    repo: "{{ item.repo }}"
    filename: "{{ item.file }}"
    validate_certs: yes
    update_cache: yes
  register: result
  until: result is succeeded
  retries: 30
  delay: 10
  become: yes
  with_items:
    - "{{ apt_repositories }}"
  notify: Update apt cache

# Force handlers to run
- meta: flush_handlers
