---
- name: Clone personal utils
  git:
    repo: "{{ my_utils_repo }}"
    dest: "{{ my_utils_src_dir }}"

- name: Find personal scripts
  find:
    paths: "{{ my_utils_src_dir }}"
    patterns: "*.bash"
  register: find

- name: Symlink personal scripts
  file:
    src: "{{ item.path }}"
    path: "{{ ansible_env.HOME }}/bin/{{ (item.path | basename | splitext)[0] }}"
    state: link
  with_items: "{{ find.files }}"
