---
- name: Create Eclipse directory in home dir
  file:
    dest="{{ eclipse_install_dir }}"
    state=directory

- name: Download and extract Eclipse in home dir
  unarchive:
    src: "{{ eclipse_download_url }}"
    dest: "{{ eclipse_install_dir }}"
    remote_src: yes
    extra_opts: "--strip-components=1"
  register: eclipse_download

- name: Symlink Eclipse binary
  file:
    src: "{{ eclipse_install_dir }}/eclipse"
    path: "{{ ansible_env.HOME }}/bin/eclipse"
    state: link
  when: eclipse_download.changed
