---
- name: Check if IntelliJ archive is already present
  stat:
    path: "{{ intellij_download_path }}"
  register: intellij_archive

- name: Create download directory
  file:
    state: directory
    dest: "{{ intellij_download_dir }}"
  when: not intellij_archive.stat.exists

- name: Download IntelliJ
  get_url:
    url: "{{ intellij_download_url }}"
    dest: "{{ intellij_download_dir }}/{{ intellij_filename }}"
  when: not intellij_archive.stat.exists

- name: Create installation directory
  file:
    state: directory
    dest: "{{ intellij_install_dir }}"

- name: Extract IntelliJ in installation directory
  unarchive:
    src: "{{ intellij_download_path }}"
    extra_opts: "--strip-components=1"
    dest: "{{ intellij_install_dir }}"
    creates: "{{ intellij_install_dir }}/bin"

- name: Symlink IntelliJ binary
  file:
    src: "{{ intellij_install_dir }}/bin/idea.sh"
    path: "{{ ansible_env.HOME }}/bin/intellij"
    state: link
