---
- name: Creation of the .ssh directory
  file:
    path: ~/.ssh
    state: directory

- name: Generate a new SSH key
  openssh_keypair:
    path: "~/.ssh/{{ ssh_key_name }}"
    type: ed25519
  register: ssh_key

- name: Deploy key to Github
  uri:
    url: "https://api.github.com/user/keys"
    method: POST
    body:
      title: "{{ lookup('file', '/etc/machine-id') }}"
      key: "{{ ssh_key.public_key }}"
      read_only: false
    body_format: json
    status_code:
      - 201
      - 200
      - 422
    headers:
      Authorization: "token {{ github_access_token }}"
