---
- name: Download greenclip
  get_url:
    url: "{{ greenclip_download_url }}"
    dest: "{{ greenclip_install_dir }}"

- name: Make greenclip executable
  file: "dest={{ greenclip_install_dir }}/greenclip mode=u+x"
